import { DEFAULT_BOARD_ID } from '@/shared/config/ids';
import type { ColumnId } from '@/shared/config/columns';
import type { Task } from './types';

const NOW = '2026-05-06T09:00:00.000Z';

export const SEED_TASKS_BY_COLUMN: Record<ColumnId, Task[]> = {
  todo: [
    {
      id: 't-1',
      boardId: DEFAULT_BOARD_ID,
      title: 'Купить продукты на неделю',
      description: 'Молоко, хлеб, яйца, овощи, фрукты.',
      priority: 'high',
      tags: ['покупки', 'дом'],
      deadline: '2026-05-09T00:00:00.000Z',
      assigneeId: 'u-anna',
      createdAt: NOW,
    },
    {
      id: 't-2',
      boardId: DEFAULT_BOARD_ID,
      title: 'Записаться к стоматологу',
      description: 'Ежегодный осмотр, лучше утром.',
      priority: 'medium',
      tags: ['здоровье'],
      deadline: '2026-05-20T00:00:00.000Z',
      assigneeId: 'u-mike',
      createdAt: NOW,
    },
    {
      id: 't-3',
      boardId: DEFAULT_BOARD_ID,
      title: 'Продлить абонемент в зал',
      description: 'Скидка на годовой действует до конца месяца.',
      priority: 'low',
      tags: ['здоровье', 'финансы'],
      deadline: '2026-05-28T00:00:00.000Z',
      assigneeId: 'u-mike',
      createdAt: NOW,
    },
  ],
  'in-progress': [
    {
      id: 't-4',
      boardId: DEFAULT_BOARD_ID,
      title: 'Спланировать день рождения Анны',
      description: 'Выбрать место, разослать приглашения, заказать торт.',
      priority: 'high',
      tags: ['встречи', 'дом'],
      deadline: '2026-05-15T00:00:00.000Z',
      assigneeId: 'u-mike',
      createdAt: NOW,
    },
    {
      id: 't-5',
      boardId: DEFAULT_BOARD_ID,
      title: "Прочитать 'Designing Data-Intensive Apps'",
      description: 'Сейчас на 4-й главе, цель — глава в неделю.',
      priority: 'medium',
      tags: ['учёба'],
      deadline: '2026-06-30T00:00:00.000Z',
      assigneeId: 'u-anna',
      createdAt: NOW,
    },
    {
      id: 't-6',
      boardId: DEFAULT_BOARD_ID,
      title: 'Закончить уборку на балконе',
      description: 'Разобрать старые горшки, отвезти мусор на переработку.',
      priority: 'low',
      tags: ['дом'],
      deadline: '2026-05-18T00:00:00.000Z',
      assigneeId: null,
      createdAt: NOW,
    },
  ],
  done: [
    {
      id: 't-7',
      boardId: DEFAULT_BOARD_ID,
      title: 'Оплатить счёт за электричество',
      description: 'Оплачено через интернет-банк.',
      priority: 'high',
      tags: ['финансы', 'дом'],
      deadline: '2026-05-04T00:00:00.000Z',
      assigneeId: 'u-anna',
      createdAt: NOW,
    },
    {
      id: 't-8',
      boardId: DEFAULT_BOARD_ID,
      title: 'Забрать вещи из химчистки',
      description: 'Из той, что рядом с офисом.',
      priority: 'medium',
      tags: ['дела'],
      deadline: '2026-05-03T00:00:00.000Z',
      assigneeId: 'u-mike',
      createdAt: NOW,
    },
    {
      id: 't-9',
      boardId: DEFAULT_BOARD_ID,
      title: 'Продлить паспорт',
      description: 'Новый действует до 2036 года.',
      priority: 'low',
      tags: ['документы', 'путешествия'],
      deadline: '2026-05-02T00:00:00.000Z',
      assigneeId: 'u-anna',
      createdAt: NOW,
    },
  ],
};
